### ISSUE TITLE
How to alert if the field value is larger then 50?

### ISSUE THREAD

**Issue by creamJelly** [airbus-cyber/graylog-plugin-aggregation-count#1]
I have some log that struct like below
`{"type":"ItemException","GameSvrId":"game-000-0001","EventTime":"2019-02-18 19:43:23","GameAppId":"loveworld-local","PlatId":2,"LoginChannel":"unity-editor","OpenId":"dt201901161950","RoleId":37017695861859,"Format":"1.0.0","Sequence":1550490199,"ItemId":121,"ItemType":12,"OperateType":0,"Num":5,"NumberNum":5}`

and I want to be alertd if the value of "NumberNum" is larger then 50 and need to group by "RoleId"

I make the configure like below, but it seems not work.
![image](https://user-images.githubusercontent.com/10293381/52949166-75818e00-33b6-11e9-8442-bb99e6c4650f.png)

so what should I do ? If I there is someting wrong with my config?

**Comment by dlancelin** [comment]
Hi,

Please configure a **stream** to receive your log with the following rule:
`field "NumberNum" greater than 50`

Then configure the **plugin** as follows:
`distinction_fields: <empty>`   
`grouping_fields: RoleId`   
`threshold: 0`   
`threshold_type: MORE`   

Apply the configuration of the plugin to the stream defined above.

Tell me if it works!
