### ISSUE TITLE
Throw the right exception to get more context

### ISSUE THREAD

**Issue by frantz45** [airbus-cyber/graylog-plugin-aggregation-count#12]
When an error occurred the wrong exception is thrown so Graylog is not able to give us more context to understand what happened.

I think this issue is also present in the Correlation Count plugin.

Related logs :

`[EventProcessorExecutionJob] Event processor <aggregation-count/5f97c5d27768f006933560b5> failed to execute: Couldn't create events for: EventDefinitionDto{id=5f97c5d27768f006933560b5, title=abcdef12345, description=Generated by the alert wizard, priority=2, alert=true, config=AggregationCountProcessorConfig{type=aggregation-count, stream=5f97c5d27768f006933560ac, thresholdType=MORE, threshold=0, groupingFields=[], distinctionFields=[], comment=Generated by the alert wizard, searchQuery=*, searchWithinMs=60000, executeEveryMs=60000}, fieldSpec={}, keySpec=[], notificationSettings=EventNotificationSettings{gracePeriodMs=0, backlogSize=500}, notifications=[Config{notificationId=5f97c5d27768f006933560b3, notificationParameters=Optional.empty}], storage=[Config{type=persist-to-streams-v1, streams=[000000000000000000000002]}]} (retry in 5000 ms)`

`[EventProcessorEngine] Caught an unhandled exception while executing event processor <aggregation-count/abcdef12345/5f96fda37768f006932f0e36> - Make sure to modify the event processor to throw only EventProcessorExecutionException so we get more context!`

**Comment by tomasnk** [comment]
The error is not on the plugin, but on the dependencies.
