### ISSUE TITLE
can't use distinction/grouping fields

### ISSUE THREAD

**Issue by kornflex** [airbus-cyber/graylog-plugin-aggregation-count#2]
Hello,

I have Graylog 3.
I'm trying to be alerted when an IP is trying to bruteforce my mail server.

With your plugin, I add this configuration : 
```
backlog: 10
comment: <empty>
distinction_fields: <empty>
grace: 60
grouping_fields: <empty>
query: message:("error=authentication failed for" OR "authentication failed: authentication failure") AND _exists_:clientIP AND NOT clientIP_country_code:FR AND _exists_:clientIP_country_code
repeat_notifications: false
threshold: 10
threshold_type: MORE
time: 30
```

It works but not grouping alert by IP.

If I change the alert by adding : 
`distinction_fields: clientIP`

The alert sends me all my log, like as query doesn't used anymore :/

Could you help me please ?

**Comment by dlancelin** [comment]
Hi,

Instead of `distinction_fields: clientIP`, use `grouping_fields: clientIP` and let `distinction_fields: <empty>`.

Does this solve your issue ?

**Comment by kornflex** [comment]
Hello,
thank you for your response but in this case, all the mail server logs is sent :/

`Stream had 423 messages in the last 30 minutes with trigger condition more than 10 messages with the same value of the fields clientIP`

Example of email alert : 

`source: zmstore2 | message: Feb 26 13:13:12 zmmta4 postfix/smtpd[26938]: disconnect from xxxxxxx[xxxxxxx] { offset: 848972590 | gl2_remote_ip: 192.168.9. | gl2_remote_port: 33684 | streams: [5c5aa6f582e4200209a034cc] | type: null | gl2_source_input: 5c5aa5df82e4200209a03392 | file: /var/log/zimbra.log | clientIP: 192.168.11. | name: zmstore2 | gl2_source_node: 1a456cf3-4030-47c9-beaa-e5712be2c067 | _id: 1220e304-39c0-11e9-af25-005056a1fe0e | facility: filebeat | timestamp: 2019-02-26T12:14:30.244Z }`

**Comment by dlancelin** [comment]
Is it the query that does not work?

**Comment by kornflex** [comment]
Yes.
I have an alert, but only for a specific IP so, I think group/distinct fields work. But when specified, query is not take anymore

thanks

**Comment by dlancelin** [comment]
The query feature was introduced with Graylog 2.5. 
However the plugin is comptaible with Graylog 2.4. 
So we are working on this issue to make a new release compatible with Graylog 2.5 and so with Graylog 3.0 so that the query functionality works.

**Comment by kornflex** [comment]
Thank you !

**Comment by i2dcarrasco** [comment]
Thanks!!

**Comment by dlancelin** [comment]
Check the new version [1.1.0](https://github.com/airbus-cyber/graylog-plugin-aggregation-count/releases/tag/1.1.0).
The release adds the Search Query feature.

**Comment by kornflex** [comment]
Thank you very much !

Hope you could do this for alert wizard plugin and others !
