### ISSUE TITLE
Build is getting failed while compiling the source

### ISSUE THREAD

**Issue by divakar525** [airbus-cyber/graylog-plugin-aggregation-count#23]
I am trying to compile the source using "mvn package" on mac. But the build is getting failed and getting below errors / exceptions. Please help me to resolve the issue

[INFO] Unpacking /Users/divagu/.m2/repository/com/github/eirslett/yarn/1.22.5/yarn-1.22.5.tar.gz into /Users/divagu/Desktop/graylog-source/graylog-plugin-aggregation-count/node/yarn
[INFO] Installed Yarn locally.
[INFO] 
[INFO] --- frontend-maven-plugin:1.9.1:yarn (yarn install) @ graylog-plugin-aggregation-count ---
[INFO] Running 'yarn install' in /Users/divagu/Desktop/graylog-source/graylog-plugin-aggregation-count
[INFO] yarn install v1.22.5
[INFO] warning ../../../package.json: No license field
[INFO] [1/4] Resolving packages...
[INFO] error Package "graylog-web-plugin" refers to a non-existing file '"/Users/divagu/Desktop/graylog-source/graylog2-server/graylog2-web-interface/packages/graylog-web-plugin"'.
[INFO] error Package "graylog-web-plugin" refers to a non-existing file '"/Users/divagu/Desktop/graylog-source/graylog2-server/graylog2-web-interface/packages/graylog-web-plugin"'.info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  46:52 min
[INFO] Finished at: 2022-01-24T16:08:56+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.9.1:yarn (yarn install) on project graylog-plugin-aggregation-count: Failed to run task: 'yarn install' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by frantz45** [comment]
You need to download the Graylog sources from https://github.com/Graylog2/graylog2-server and unzip it in /Users/divagu/Desktop/graylog-source/graylog2-server/

**Comment by frantz45** [comment]
Are you sure to need to compile this plugin ? Because we provide releases already compiled: https://github.com/airbus-cyber/graylog-plugin-aggregation-count/releases
