### ISSUE TITLE
Does it work on Graylog 3.0.0?

### ISSUE THREAD

**Issue by borjam** [airbus-cyber/graylog-plugin-aggregation-count#4]
I am trying to use this plugin to trigger a condition based on cardinality.

In my case, I am examining a stream of DNS query errors from a farm of recursive DNS servers. The stream contains only DNS query errors and fields with the self explanatory names "dns_query_name", "dns_client_addr", etc.

I am trying this configuration but despite having more than 10 distinct failed names in a 5 minute interval the condition will not trigger.

Does it work? I am using Graylog 3.0.0 and at least the wizard to configure the condition loads properly. 

`backlog: 0
comment: <empty>
distinction_fields: dns_req_name
grace: 0
grouping_fields: <empty>
query: <empty>
repeat_notifications: false
threshold: 5
threshold_type: MORE
time: 5`

Thanks!

**Comment by dlancelin** [comment]
Hi,

It should work, but I see in your configuration that the **_query_** parameter is empty.
Could you try with the parameter **_query_** set to **_\*_** ?

**Comment by borjam** [comment]
I tried with query=* and it didn't work either.

Adding a backlog parameter seems to work.  I understand that the backlog messages parameter is only used to determine how many messages to include in the notification alert? It seems to affect the actual number of messages examined.

So, if I set it to, for example, 20 minutes, and with a backlog of 10 messages it does work.

Curious.

**Comment by borjam** [comment]
Anyway, sorry for the belated update. It works on 3.0.0 although the documentation is a bit confusing.

**Comment by devicenull** [comment]
I agree with you here, the backlog description is *very* confusing.  I was having the same issue here, alerts were not firing until I raised backlog.
