### ISSUE TITLE
Wrong query when email alert

### ISSUE THREAD

**Issue by kornflex** [airbus-cyber/graylog-plugin-aggregation-count#5]
Hello,
In GL 3.0.0, with aggregation plugin 1.1.0, when an alert is sent by mail, you can have the link to graylog webUI search : 
${if stream_url}Stream URL: ${stream_url}${end}

In my case, the aggregation condition is : 

```
backlog: 50
comment: <empty>
distinction_fields: <empty>
grace: 30
grouping_fields: clientIP
query: message: "Vous avez atteint la limite d'envoi"message: "Vous avez atteint la limite d'envoi" AND _exists_:clientIP_country_code AND clientIP_country_code:FR
repeat_notifications: false
threshold: 10
threshold_type: MORE
time: 60
```

But, when I receive a mail alert, I have : 
Stream URL: https://xxxxxxxxxxxxxxxxxxxxxx/streams/5c5aa6f582e4200209a034cc/messages?rangetype=absolute&from=2019-03-20T13:47:31.456Z&to=2019-03-20T14:47:31.456Z&q=*

Query is the default one, not what I have wrote

Thank you for your help

**Comment by kornflex** [comment]
Hello,
For your information, I have updated to the lastest verion of GL 3.0.1, same error

**Comment by dlancelin** [comment]
Hello,
Does the stream URL work with other condition types (message count, field aggregation, field content) ?
Because the stream_url is exposed by Graylog and not by the plugin.

**Comment by kornflex** [comment]
Hello,
You are right, with a Message Count Alert Condition alert, URL is : q=* 

It's not your plugin.

Thank you
