### ISSUE TITLE
Include messages in email alert notification

### ISSUE THREAD

**Issue by joshabts** [airbus-cyber/graylog-plugin-aggregation-count#8]
I am using v1.2.1 of the plugin and am trying to figure out how to get it to include the "grouped" messages that met the criteria in the email notification for the alert that is raised.

My alert configuration looks like this:
```
backlog: 10000
comment: Someone created more than 50 distinct files in 5 minutes
distinction_fields: ObjectName
grace: 0
grouping_fields: SubjectUserName
query: EventID:4663 AND AccessMask:0x100
repeat_notifications: false
threshold: 50
threshold_type: MORE
time: 5
```

My notification configuration looks like this:
```
body: ##########
Alert for: ${alertCondition.title}
Alert Description: ${check_result.resultDescription}
Date: ${check_result.triggeredAt}
##########

${if backlog}Last messages accounting for this alert:
${foreach backlog message}
##########
${message}
##########
${end}${else}<No backlog>
${end}
email_receivers: <empty>
sender: graylog@domain.com
subject: Graylog alert: ${alertCondition.title}
user_receivers: johnd
```

So if I go create 50 files that causes the alert to be raised, I do get the email notification, but it shows: 
```
##########
Alert for: File Creations
Alert Description: Stream had 0 messages in the last 5 minutes with trigger condition more than 50 messages with the same value of the fields SubjectUserName, and with distinct values of the fields ObjectName. (Current grace time: 0 minutes)
Date: 2019-07-19T12:26:09.618Z
##########

<No backlog>
```

In the end, I basically am trying to say if a user creates 50 files in 5 minutes (regardless of how many messages it needs to look through), I want to get an alert notification email showing me the 50 (or more) "messages" (as they include the filename) that met the criteria for that user.

What am I missing here to make this actually work?  Or is it not possible in this scenario?

**Comment by tomasnk** [comment]
Hi Joshabts,
The problem is that you got 0 messages matching your criteria.
Did you well extract the fields: ObjectName, SubjectUserName, EventID and AccessMask?
Can you try with  "query:  *"

**Comment by joshabts** [comment]
The thing is, I only get the emails when I do match the criteria.  There
are a lot of messages going to the stream, so I'm using the query to filter
it down.

**Comment by tomasnk** [comment]
what is the distinction field "ObjectName" ?

**Comment by joshabts** [comment]
Here is an example message.  The ObjectName is the filename of the file being operated on.

Received by
Windows-EventLog on  bf91d9de / graylog.mydomain.com
Stored in index
graylog_417
Routed into streams
File Server Auditing
AccessList
%%4424
AccessMask
0x100
Category
File System
Channel
Security
EventID
4663
EventReceivedTime
2019-05-03 10:27:08
EventType
AUDIT_SUCCESS
HandleId
0x4e3c
Keywords
-9214364837600035000
ObjectName
H:\folders\username\Favorites\CRM.url
ObjectServer
Security
ObjectType
File
Opcode
Info
OpcodeValue
0
ProcessID
640
ProviderGuid
{54849625-5478-4994-A5BA-3E3B0328C30D}
RecordNumber
95532541
Severity
INFO
SeverityValue
2
SourceModuleName
in
SourceModuleType
im_msvistalog
SourceName
Microsoft-Windows-Security-Auditing
SubjectDomainName
MYDOMAIN
SubjectLogonId
0x2a4b82d7
SubjectUserName
username
SubjectUserSid
S-1-5-21-1482476501-1085031214-725345543-8255
Task
12800
ThreadID
648
Version
1
full_message
An attempt was made to access an object.

Subject:
	Security ID:		S-1-5-21-1482476501-1085031214-725345543-8255
	Account Name:		username
	Account Domain:		MYDOMAIN
	Logon ID:		0x2A4B82D7

Object:
	Object Server:		Security
	Object Type:		File
	Object Name:		H:\folders\username\Favorites\CRM.url
	Handle ID:		0x4e3c
	Resource Attributes:	

Process Information:
	Process ID:		0x4
	Process Name:		

Access Request Information:
	Accesses:		WriteAttributes
				
	Access Mask:		0x100
level
6
message
An attempt was made to access an object.

Subject:
	Security
severity
Informational (6)
(decorated)
source
fileserver.mydomain.com
timestamp
2019-05-03 10:27:07.000 -04:00

**Comment by tomasnk** [comment]
I figured it out, it's because of the backslash in your ObjectName.
