### ISSUE TITLE
Not functional

### ISSUE THREAD

**Issue by soulmaster43** [airbus-cyber/graylog-plugin-aggregation-count#9]
Hi,

I tested this plugin for Graylog version 3.1.2-1 and it is not working (as if I wasn't even installed)
Checked the logs but no errors were noticed.
![Capture](https://user-images.githubusercontent.com/19363009/65526385-52413300-def1-11e9-838a-0e23b072aef6.PNG)
![Capture2](https://user-images.githubusercontent.com/19363009/65526387-52413300-def1-11e9-9e21-ec7d7267832d.PNG)

Thank you

**Comment by tomasnk** [comment]
Hi,

The plugin Aggregation Count 1.2.X work only with Graylog 3.0.X

**Comment by soulmaster43** [comment]
Hi Thomas,

Thank you for your reply.

Are there any plans to update it in the near future?

**Comment by tomasnk** [comment]
Hi,
The plugin will be updated, I hope for the end of this year.

**Comment by Danixu** [comment]
I think that is not necessary on latest graylog 3. Now or has a filter that allow queries and also groups by field.

**Comment by tomasnk** [comment]
Please see Release 2.0.0 compatible with Graylog 3.2
